"""mails

Revision ID: 883c3da7421d
Revises: 091022f01fda
Create Date: 2025-03-18 22:41:51.363957

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = '883c3da7421d'
down_revision = '091022f01fda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('status', sa.Enum('SENT', 'FAILED', name='mailandpushsentstatus'), nullable=False))
    op.add_column('mails', sa.Column('sent_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mails', 'sent_at')
    op.drop_column('mails', 'status')
    # ### end Alembic commands ###
