"""mails

Revision ID: 091022f01fda
Revises: efeda579512a
Create Date: 2025-03-18 22:24:14.787923

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = '091022f01fda'
down_revision = 'efeda579512a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'mails',
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('body', sa.String(), nullable=False),
        sa.Column('to_email', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_mails')),
    )
    op.create_index(op.f('ix_mails_id'), 'mails', ['id'], unique=True)
    op.create_index('ix_mails_to_email', 'mails', ['to_email'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mails_to_email', table_name='mails', postgresql_using='btree')
    op.drop_index(op.f('ix_mails_id'), table_name='mails')
    op.drop_table('mails')
    # ### end Alembic commands ###
